server:
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /api
  port: 8081
spring:
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  profiles:
    active: dev



