server:
  tomcat:
    uri-encoding: UTF-8

  servlet:
    context-path: /Manage
  port: 8080
spring:
  banner:
    charset: UTF-8
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  messages:
    encoding: UTF-8
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    encoding: UTF-8
    mode: HTML
    suffix: .html
  profiles:
    active: dev

